### ISSUE TITLE
Plugin Updater

### ISSUE THREAD

**Issue by nuttyNaoko** [Jaimss/jcore#1]
check discord convo

**Comment by Jaimss** [comment]
Moving convo here -
Updated might look something like this in practice. A command like `/updateplugins` would look in a `update_plugins.yml` file.
```yml
plugins_to_update:
    PlaceholderAPI: 6245
    JCore: 86911
    # etc etc
```

fetch each of those plugins and download them to the `plugins` folder & restart the server. maybe use the name provided to match a jar already in the `plugins` folder to delete it to avoid duplicates.

probably will only work for non-premium plugins. maybe use [spiget](https://spiget.org/documentation/#!/resources/get_resources_resource_download) for downloads.
